variables:
  serpent5_Version: 3.1.0

pool:
  vmImage: windows-latest

name: $(serpent5_Version)$(Rev:.r)

steps:
  - script: dotnet restore
    displayName: dotnet restore
  - script: dotnet build -c Release --no-restore /p:Version=$(Build.BuildNumber) /p:InformationalVersion=$(serpent5_Version)
    displayName: dotnet build
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*.Test.csproj'
      arguments: -c Release --no-build --collect "Code Coverage"
    displayName: dotnet test
  - script: dotnet pack -c Release -o $(Build.ArtifactStagingDirectory) --no-build /p:PackageVersion=$(serpent5_Version)
    displayName: dotnet pack
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: $(Build.DefinitionName)-$(Build.BuildNumber)
